parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $projectDir: '%kernel.project_dir%'

    Insitaction\EasyCropBundle\Form\:
        resource: '../src/Form'
